#!/usr/bin/env python3
"""Convert markdown reports to styled HTML (can be printed to PDF from browser)"""
import markdown
import sys
import os

def convert(md_path, out_path=None):
    with open(md_path) as f:
        md_text = f.read()

    html_body = markdown.markdown(md_text, extensions=['tables', 'fenced_code'])

    if not out_path:
        out_path = md_path.replace('.md', '.html')

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Cross-Border Arbitrage Report</title>
<style>
body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; line-height: 1.6; }}
h1 {{ color: #1a1a2e; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
h2 {{ color: #16213e; margin-top: 30px; }}
h3 {{ color: #0f3460; }}
table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #16213e; color: white; }}
tr:nth-child(even) {{ background: #f9f9f9; }}
code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
blockquote {{ border-left: 4px solid #e94560; margin: 15px 0; padding: 10px 20px; background: #fff5f5; }}
hr {{ border: none; border-top: 1px solid #eee; margin: 30px 0; }}
@media print {{ body {{ max-width: 100%; margin: 20px; }} }}
</style></head><body>
{html_body}
<footer style="margin-top:40px;padding-top:20px;border-top:1px solid #eee;color:#999;font-size:0.9em;">
<p>Generated by Global Arbitrage Intelligence System | {os.path.basename(md_path)} | Print to PDF: Ctrl+P</p>
</footer>
</body></html>"""

    with open(out_path, 'w') as f:
        f.write(html)
    print(f"✅ {out_path}")
    return out_path

if __name__ == '__main__':
    reports_dir = os.path.expanduser("~/cowork-brain/projects/global-arbitrage/data/reports/")
    for fname in os.listdir(reports_dir):
        if fname.endswith('.md'):
            convert(os.path.join(reports_dir, fname))
